services:
  - type: web
    name: kinex-helper-bot
    runtime: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
